import { defineConfig } from 'astro/config';

// base/site are env-overridable so the SAME repo builds for two targets WITHOUT
// touching the committed defaults:
//   - GitHub Pages staging (defaults):  base '/tik-website', site github.io
//   - Cloudflare Pages / apex go-live:  TIK_BASE_PATH='/'  TIK_SITE='https://tourinkohsamui.com'
// Every booking CTA still links to the live tourinkohsamui.com product page,
// so the cart / n8n / Vercel pipeline is never touched.
const BASE = process.env.TIK_BASE_PATH ?? '/tik-website';
const SITE = process.env.TIK_SITE ?? 'https://tisaautomation.github.io';
// Optional outDir override (TIK_OUT_DIR) — lets us build to a path OUTSIDE the
// OneDrive-synced project dir, so OneDrive doesn't restore stale build artifacts
// mid-build (which pollutes dist and drops shared CSS links). Defaults to ./dist.
const OUT = process.env.TIK_OUT_DIR || './dist';

export default defineConfig({
  site: SITE,
  base: BASE,
  outDir: OUT,

  // 'always': inline ALL CSS into each page → zero render-blocking stylesheet
  // requests (the LCP killer on the text-LCP pages). Worth the small HTML bump
  // for a mostly-static marketing site; paints instantly, no extra round-trip.
  build: { inlineStylesheets: 'always' },

  compressHTML: true,

  // Allow the preview server to be reached via the Cloudflare quick-tunnel / Pages host.
  // preserveSymlinks: keep the no-space junction path instead of resolving to the OneDrive
  // realpath ("…/Website Designer/…") — the space in that path breaks CSS emit on Windows.
  vite: { resolve: { preserveSymlinks: true }, preview: { allowedHosts: ['.trycloudflare.com', '.pages.dev'], host: true } },
  // Sitemap is generated by our own src/pages/sitemap.xml.ts endpoint (deterministic,
  // robust to the custom outDir + OneDrive junction). @astrojs/sitemap broke on this setup.
});